### ISSUE TITLE
White Screen appears after upgrade UIWebView to WKWebView Plugin

### ISSUE THREAD

**Issue by saqib-dev** [apache/cordova-plugin-wkwebview-engine#141] opened 2020-04-06 14:02 UTC
After installing cordova-plugin-wkwebview-engine plugin my cordova ios app, its giving white screen after the splash screen.

Login Screen should be appear.

I have Angular 8 application and i am using cordova framework for ios and android applications build. IOS app was running fine before i added the  cordova-plugin-wkwebview-engine. I added thing because play store deprecated the UIWebview.  Xocde running the application on simulator but when apps launch it show first splash screen and after that it appears white screen and it app got stuck into it. i have added proper config.xml tag according to plugin documentation on npm.

### Environment, Platform, Device
iPhone 11 Pro Max Simulator, iOS 13.4 
iPhone 11 Pro, iOS 13.4
iPhone 8 Plus , iOS 13.4

### Version information
Cordova:

9.0.0 (cordova-lib@9.0.1)
cordova-plugin-device: 2.0.3
cordova-plugin-wkwebview-engine:1.2.1
React:

react: 16.13.0
XCode: 11.3.1
MacOS Catalina 10.15.2

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment] 2020-04-06 14:08
Duplicate of #139 - please help to gather information in that issue

**Closed by timbru31** 2020-04-06 14:08 UTC

**Comment by saqib-dev** [comment] 2020-04-06 14:12
#139 this one is also closed.
