### ISSUE TITLE
Can I display detailed Javascript ERROR messages?

### ISSUE THREAD

**Issue by ragcsalo** [apache/cordova-plugin-wkwebview-engine#154] opened 2020-05-26 16:37 UTC
Whenever WKWebView encounters a Javascript error, I only get "Script error" in the XCode console. This makes debugging very slow and difficult... Is there a way I could display detailed error messages?

Now I use this code:

```
window.onerror = function (msg, url, lineNo, columnNo, error) {
  console.log('JavaScript ERROR: ['+msg+'] in '+url+' at line '+lineNo+' column '+columnNo);
  console.log('ERROR: '+JSON.stringify(error));
  return false;
}
```

which results in this:

> JavaScript ERROR: [Script error.] in at line 0 column 0
> ERROR: null

**Comment by breautek** [comment] 2020-05-26 16:47
These are [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) errors and is obfuscated by design (frustrating, I know). There is no way to see the error in the client.

If you're trying to contact a remote server, you may see something useful in the server web server logs. Chances are you're missing an appropriate `Access-Control` header.

If you're trying to use XHR to fetch a local resource* (like a `file://` resource, common with angular apps that uses angular templates), then you need a third-party plugin such as [cordova-plugin-wkwebview-file-xhr](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr) which works around CORS issues by using the native layer http client and omitting the origin header altogether. This plugin only works for using local XHR requests to the filesystem.

*It would be better to use the cordova-plugin-file to read files from the local  filesystem if possible, but in some situations that can difficult to do.

**Comment by ragcsalo** [comment] 2020-05-26 16:55
I just include a local javascript file from the www directory (no path needed). So there's no way I can display Javascript errors then? :-/

**Comment by breautek** [comment] 2020-05-26 17:00
You shouldn't be seeing this on a local js file. Only XHR requests to the `file://` protocol (because WKWebView treats it as cross-origin) or trying to load a resource from a webserver that doesn't have CORS configured.

**Comment by ragcsalo** [comment] 2020-05-26 17:27
Yeah, that's odd... I get this **[Script error.]** even if I run a buggy javascript code in my index.html inside a `<script> </script>` tag. No other hint what or where the problematic code could be... very frustrating. Anyway, I'll look for a solution in some forums, maybe I'll be lucky. :-)

**Comment by breautek** [comment] 2020-05-26 17:41
You can try attaching the `crossorigin` attribute on the `script` tag, it may at least give you some more information.

From MDN:
>When an error occurs in a script, loaded from a different origin, the details of the error are not reported to prevent leaking information (see bug 363897). Instead the error reported is simply "Script error." This behavior can be overriden in some browsers using the crossorigin attribute on <script> and having the server send the appropriate CORS HTTP response headers.

Also alerting the error message also appears to be a workaround I guess, according to [MDN notes](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror#Notes). But that seems strange to me as you've already tried something similar, the only difference is that you were using `console.log` and MDN is using `alert`...

**Comment by breautek** [comment] 2020-05-26 17:43
Since this isn't really a bug, I'll be closing this ticket, but if you have any other questions, feel free to ask in our [slack](http://slack.cordova.io/).

**Closed by breautek** 2020-05-26 17:43 UTC
Labels: support
