### ISSUE TITLE
Ignoring request to load this main resource because it is outside the sandbox 

### ISSUE THREAD

**Issue by araafat3** [apache/cordova-plugin-wkwebview-engine#176] opened 2020-09-29 13:11 UTC
# Bug Report
Sandbox Issue - WebPageProxy::Ignoring request to load this main resource because it is outside the sandbox 
## Problem
that webkit can not load local index files
### What is expected to happen?

can load local file from iphone

### What does actually happen?

app Stuck on splash screen

Environment, Platform, Device
iOS 13.2.2, cordova-ios 5.1.1, iPhone 6S

Version information
cordova-cli 9.0.0

**Comment by breautek** [comment] 2020-10-07 04:38
First I'd make sure the files you are attempting to load the webview is indeed within the app bundle (which is your "sandbox").

If so, then you're likely hitting one of the known WKWebView [bugs](https://bugs.webkit.org/show_bug.cgi?id=154916). I'd suggest upgrading to cordova-ios@6 and use [schemes](https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html). Note that as of cordova-ios@6, this plugin is obsolete and is not compatible.

**Comment by breautek** [comment] 2020-10-07 04:46
Duplicate of https://github.com/apache/cordova-plugin-wkwebview-engine/issues/56

**Closed by breautek** 2020-10-07 04:46 UTC
