### ISSUE TITLE
Open an html file from unzipped file throwing Received an unexpected URL from the web process|WebPageProxy::Ignoring request to load this main resource because it is outside the sandbox

### ISSUE THREAD

**Issue by SapiensEduvision** [apache/cordova-plugin-wkwebview-engine#173] opened 2020-09-02 22:01 UTC
# Bug Report

I'm new to cordova ios, sorry if this don't belong here

This is the log I'm getting

[CDVFileTransfer download:] [Line 423] File Transfer downloading file...
[CDVFileTransferDelegate connection:didReceiveResponse:] [Line 771] Streaming to file /Users/mac5/Library/Developer/CoreSimulator/Devices/D1C355EC-496B-4306-ACE4-49A62BDFB839/data/Containers/Data/Application/1766AB55-7D30-4E59-851C-93D2E88D13CF/sapiens_zips/act2_InterrelacionEntreSistemas.zip
File Transfer Finished with response code 200
CDVFileTransferDelegate connectionDidFinishLoading:] [Line 637] File Transfer Download success
[Loading] Received an unexpected URL from the web process
WebPageProxy::Ignoring request to load this main resource because it is outside the sandbox

Im trying to open an index.html that is contained in the zip file

## Problem
The download and unzip of the file is working I think, the problem comes after, because the index.html that is in the .zip file doesn't open
### What is expected to happen?

Download, unzip and open the html of the zip file

### What does actually happen?

The file is downloaded and unzipped but after that nothing happens and the console brings that message

## Information

Cordova CLI 10.0.0

cordova ios 6.1.1
cordova-plugin-file-downloader 0.4.0 "Downloader"
cordova-plugin-file-md5 0.3.3 "MD5 Checksum"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"

### Environment, Platform, Device
Xcode 11.7 beta, iOS 13 running on simulator

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2020-10-07 04:45
Duplicate of https://github.com/apache/cordova-plugin-wkwebview-engine/issues/56

**Closed by breautek** 2020-10-07 04:45 UTC
